name: fairplay_ds
description: A new Flutter package project.
version: 2.1.2+1
publish_to: "none"
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  foundation:
    path: ./../foundation
  # git:
  #   url: git@github.com:grupo-sbf/foundation
  #   ref: "develop"
  cached_network_image: 3.2.1
  carousel_slider: 4.1.1
  copy_with_extension: 4.0.2
  chopper: 4.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: 5.0.2
  flutter_credit_card: 3.0.1
  flutter_svg: 0.22.0
  universal_platform: 1.0.0+1
  url_launcher: 6.1.2
  shimmer: 2.0.0
  flutter_staggered_animations: 1.0.0
  dartz: ^0.10.1

dependency_overrides:
  flutter_staggered_animations:
    git:
      url: https://github.com/mobiten/flutter_staggered_animations.git
      ref: 88ef999433f129b3c19e22ea5348e6543983a011

dev_dependencies:
  analyzer: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: 5.2.0
  copy_with_extension_gen: 4.0.2
  build_runner: ^2.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
