name: foundation_generator
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  injectable: 1.5.3
  build_runner: ^2.2.0
  flutter_lints: 2.0.1
  build_test: ^2.1.3
  test: ^1.17.12
  build: ^2.1.0
  source_gen: ^1.1.0
  path: ^1.8.0
  glob: ^2.0.1
  analyzer: ^4.0.0
  code_builder: ^4.1.0
  dart_style: ^2.0.3
  collection: ^1.15.0
  package_config: ^2.1.0
  injectable_generator: ^1.5.4

dev_dependencies:
